### ISSUE TITLE
i need help :P

### ISSUE THREAD

**Issue by ssllllll** [Gopro336/PSA-how-to-fix-gradle-builds-feb-2021#6]
So, im draging my new project folder to Intellij, when it starts to index in the files i get this log,

```
Could not resolve all files for configuration ':runtimeClasspathCopy'.
> Could not find net.minecraftforge:forge:1.12.2-14.23.5.2855_mapped_stable_39-1.12.
  Searched in the following locations:
    - file:/C:/Users/mader/.gradle/caches/forge_gradle/bundeled_repo/net/minecraftforge/forge/1.12.2-14.23.5.2855_mapped_stable_39-1.12/forge-1.12.2-14.23.5.2855_mapped_stable_39-1.12.pom
    - file:/C:/Users/mader/.gradle/caches/forge_gradle/bundeled_repo/net/minecraftforge/forge/1.12.2-14.23.5.2855_mapped_stable_39-1.12/forge-1.12.2-14.23.5.2855_mapped_stable_39-1.12.jar
  Required by:
      project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

I cant do setupDecompWorkspace 

![image](https://user-images.githubusercontent.com/86989232/149472682-63dd24a5-c725-43df-827b-7b744d265330.png)

any solution? i need help 😢

**Comment by Gopro336** [comment]
try hitting the refresh button
<img width="45" alt="Screen Shot 2022-01-15 at 9 38 02 AM" src="https://user-images.githubusercontent.com/63124240/149625683-1557435e-5bc8-4d24-bba6-28dad9257142.png">

**Comment by Gopro336** [comment]
If that doesn't work, manually do setupdecompworspace in the terminal

**Comment by ssllllll** [comment]
i clicked the refresh gradle button tons of times and still got the same issue but it was my fault cus i had some bad things on the build.gradle haha srry
